version: '3'
services: 
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_password
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - '3050:80'
  api-watch:
    build:
      dockerfile: Dockerfile
      context: ./back-end
    volumes:
      - /app/node_modules
      - ./back-end:/app
    command: ['yarn','watch']

  api:
    build:
      dockerfile: Dockerfile
      context: ./back-end
    ports:
     - 4000:4000
    volumes:
      - /app/node_modules
      - ./back-end:/app
    environment:
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./front-end
    ports:
     - 8000:8000
    volumes:
      - /app/node_modules
      - ./front-end:/app